// Generated by scripts/generate-elevenlabs-reading-phoneme-pack.mjs. Do not edit by hand.
// These are isolated phonemes; whole-word reading uses local Lily clips through VoiceManager.

export const READING_PHONEME_BASE_PATH = "/audio/reading/nl/elevenlabs-lily-v3/phonemes/";

export const READING_PHONEME_FILES: Record<string, string> = {
  "a": "a.mp3",
  "aa": "aa.mp3",
  "au": "au.mp3",
  "b": "b.mp3",
  "d": "d.mp3",
  "e": "e.mp3",
  "ee": "ee.mp3",
  "ei": "ei.mp3",
  "eu": "eu.mp3",
  "f": "f.mp3",
  "h": "h.mp3",
  "i": "i.mp3",
  "ie": "ie.mp3",
  "ij": "ij.mp3",
  "k": "k.mp3",
  "l": "l.mp3",
  "m": "m.mp3",
  "n": "n.mp3",
  "o": "o.mp3",
  "oe": "oe.mp3",
  "oo": "oo.mp3",
  "ou": "ou.mp3",
  "p": "p.mp3",
  "r": "r.mp3",
  "s": "s.mp3",
  "t": "t.mp3",
  "u": "u.mp3",
  "ui": "ui.mp3",
  "uu": "uu.mp3",
  "v": "v.mp3",
  "w": "w.mp3",
  "z": "z.mp3"
};

export const READING_PHONEME_KEYS = new Set<string>(Object.keys(READING_PHONEME_FILES));
